[package]
name = "rust-app"
version = "0.1.0"
authors = ["adam <ant1441@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rand = "0.7.3"
